import type { Language } from "./i18n";

const text = {
  "pt-BR": { back: "Voltar ao workspace", account: "Conta", appearance: "Aparência", language: "Idioma", overview: "Visão geral", history: "Histórico", freeCredits: "Créditos grátis", buyCredits: "Comprar créditos", wallet: "Carteira", credits: "Créditos", walletDescription: "Aqui estão os créditos da sua conta.", available: "Total disponível", dailyCredits: "Créditos diários", purchased: "Comprados", historyDescription: "Ganhos e gastos da sua conta", freeDescription: "Créditos diários, convites e anúncios", buyDescription: "Pacotes simples e econômicos", settings: "Configurações", settingsDescription: "Personalize sua conta em seções independentes.", accountDescription: "Nome de preferência e dados da conta", appearanceDescription: "Tema claro ou escuro", languageDescription: "Idioma permanente da interface" },
  "en-US": { back: "Back to workspace", account: "Account", appearance: "Appearance", language: "Language", overview: "Overview", history: "History", freeCredits: "Free credits", buyCredits: "Buy credits", wallet: "Wallet", credits: "Credits", walletDescription: "Here are your account credits.", available: "Total available", dailyCredits: "Daily credits", purchased: "Purchased", historyDescription: "Your account earnings and spending", freeDescription: "Daily credits, referrals and ads", buyDescription: "Simple and affordable packages", settings: "Settings", settingsDescription: "Customize your account in separate sections.", accountDescription: "Preferred name and account details", appearanceDescription: "Light or dark theme", languageDescription: "Permanent interface language" },
  "es-ES": { back: "Volver al espacio de trabajo", account: "Cuenta", appearance: "Apariencia", language: "Idioma", overview: "Resumen", history: "Historial", freeCredits: "Créditos gratis", buyCredits: "Comprar créditos", wallet: "Billetera", credits: "Créditos", walletDescription: "Aquí están los créditos de tu cuenta.", available: "Total disponible", dailyCredits: "Créditos diarios", purchased: "Comprados", historyDescription: "Ganancias y gastos de tu cuenta", freeDescription: "Créditos diarios, invitaciones y anuncios", buyDescription: "Paquetes simples y económicos", settings: "Configuración", settingsDescription: "Personaliza tu cuenta en secciones independientes.", accountDescription: "Nombre preferido y datos de la cuenta", appearanceDescription: "Tema claro u oscuro", languageDescription: "Idioma permanente de la interfaz" },
  "fr-FR": { back: "Retour à l’espace de travail", account: "Compte", appearance: "Apparence", language: "Langue", overview: "Vue d’ensemble", history: "Historique", freeCredits: "Crédits gratuits", buyCredits: "Acheter des crédits", wallet: "Portefeuille", credits: "Crédits", walletDescription: "Voici les crédits de votre compte.", available: "Total disponible", dailyCredits: "Crédits quotidiens", purchased: "Achetés", historyDescription: "Gains et dépenses de votre compte", freeDescription: "Crédits quotidiens, invitations et annonces", buyDescription: "Packs simples et économiques", settings: "Paramètres", settingsDescription: "Personnalisez votre compte par sections.", accountDescription: "Nom préféré et détails du compte", appearanceDescription: "Thème clair ou sombre", languageDescription: "Langue permanente de l’interface" },
  "de-DE": { back: "Zurück zum Workspace", account: "Konto", appearance: "Darstellung", language: "Sprache", overview: "Übersicht", history: "Verlauf", freeCredits: "Kostenlose Credits", buyCredits: "Credits kaufen", wallet: "Guthaben", credits: "Credits", walletDescription: "Hier sind die Credits Ihres Kontos.", available: "Insgesamt verfügbar", dailyCredits: "Tägliche Credits", purchased: "Gekauft", historyDescription: "Einnahmen und Ausgaben Ihres Kontos", freeDescription: "Tägliche Credits, Einladungen und Anzeigen", buyDescription: "Einfache und günstige Pakete", settings: "Einstellungen", settingsDescription: "Passen Sie Ihr Konto in einzelnen Bereichen an.", accountDescription: "Bevorzugter Name und Kontodaten", appearanceDescription: "Helles oder dunkles Design", languageDescription: "Dauerhafte Sprache der Oberfläche" },
  "it-IT": { back: "Torna al workspace", account: "Account", appearance: "Aspetto", language: "Lingua", overview: "Panoramica", history: "Cronologia", freeCredits: "Crediti gratuiti", buyCredits: "Acquista crediti", wallet: "Portafoglio", credits: "Crediti", walletDescription: "Ecco i crediti del tuo account.", available: "Totale disponibile", dailyCredits: "Crediti giornalieri", purchased: "Acquistati", historyDescription: "Entrate e spese del tuo account", freeDescription: "Crediti giornalieri, inviti e annunci", buyDescription: "Pacchetti semplici ed economici", settings: "Impostazioni", settingsDescription: "Personalizza il tuo account in sezioni separate.", accountDescription: "Nome preferito e dati dell’account", appearanceDescription: "Tema chiaro o scuro", languageDescription: "Lingua permanente dell’interfaccia" },
  "ja-JP": { back: "ワークスペースに戻る", account: "アカウント", appearance: "外観", language: "言語", overview: "概要", history: "履歴", freeCredits: "無料クレジット", buyCredits: "クレジットを購入", wallet: "ウォレット", credits: "クレジット", walletDescription: "アカウントのクレジットです。", available: "利用可能な合計", dailyCredits: "毎日のクレジット", purchased: "購入済み", historyDescription: "アカウントの獲得と利用", freeDescription: "毎日のクレジット、招待、広告", buyDescription: "シンプルでお得なパッケージ", settings: "設定", settingsDescription: "アカウントをセクションごとにカスタマイズします。", accountDescription: "優先名とアカウント情報", appearanceDescription: "ライトまたはダークテーマ", languageDescription: "固定されたインターフェース言語" },
  "ko-KR": { back: "워크스페이스로 돌아가기", account: "계정", appearance: "화면", language: "언어", overview: "개요", history: "기록", freeCredits: "무료 크레딧", buyCredits: "크레딧 구매", wallet: "지갑", credits: "크레딧", walletDescription: "계정의 크레딧입니다.", available: "사용 가능 합계", dailyCredits: "일일 크레딧", purchased: "구매됨", historyDescription: "계정의 적립 및 사용", freeDescription: "일일 크레딧, 초대 및 광고", buyDescription: "간단하고 경제적인 패키지", settings: "설정", settingsDescription: "계정을 섹션별로 맞춤 설정합니다.", accountDescription: "선호 이름 및 계정 정보", appearanceDescription: "라이트 또는 다크 테마", languageDescription: "영구 인터페이스 언어" },
  "zh-CN": { back: "返回工作区", account: "账户", appearance: "外观", language: "语言", overview: "概览", history: "历史记录", freeCredits: "免费积分", buyCredits: "购买积分", wallet: "钱包", credits: "积分", walletDescription: "这里是你的账户积分。", available: "可用总额", dailyCredits: "每日积分", purchased: "已购买", historyDescription: "账户的获得和使用", freeDescription: "每日积分、邀请和广告", buyDescription: "简单实惠的套餐", settings: "设置", settingsDescription: "在不同部分自定义你的账户。", accountDescription: "偏好名称和账户信息", appearanceDescription: "浅色或深色主题", languageDescription: "固定界面语言" },
  "hi-IN": { back: "वर्कस्पेस पर वापस जाएँ", account: "खाता", appearance: "दिखावट", language: "भाषा", overview: "अवलोकन", history: "इतिहास", freeCredits: "मुफ्त क्रेडिट", buyCredits: "क्रेडिट खरीदें", wallet: "वॉलेट", credits: "क्रेडिट", walletDescription: "यहाँ आपके खाते के क्रेडिट हैं।", available: "कुल उपलब्ध", dailyCredits: "दैनिक क्रेडिट", purchased: "खरीदे गए", historyDescription: "आपके खाते की कमाई और खर्च", freeDescription: "दैनिक क्रेडिट, आमंत्रण और विज्ञापन", buyDescription: "सरल और किफायती पैकेज", settings: "सेटिंग्स", settingsDescription: "अपने खाते को अलग-अलग अनुभागों में अनुकूलित करें।", accountDescription: "पसंदीदा नाम और खाते का विवरण", appearanceDescription: "लाइट या डार्क थीम", languageDescription: "स्थायी इंटरफ़ेस भाषा" },
  "ar-SA": { back: "العودة إلى مساحة العمل", account: "الحساب", appearance: "المظهر", language: "اللغة", overview: "نظرة عامة", history: "السجل", freeCredits: "أرصدة مجانية", buyCredits: "شراء أرصدة", wallet: "المحفظة", credits: "الأرصدة", walletDescription: "هذه أرصدة حسابك.", available: "الإجمالي المتاح", dailyCredits: "الأرصدة اليومية", purchased: "تم شراؤها", historyDescription: "أرباح ومصروفات حسابك", freeDescription: "أرصدة يومية ودعوات وإعلانات", buyDescription: "حزم بسيطة واقتصادية", settings: "الإعدادات", settingsDescription: "خصص حسابك في أقسام منفصلة.", accountDescription: "الاسم المفضل وتفاصيل الحساب", appearanceDescription: "المظهر الفاتح أو الداكن", languageDescription: "لغة الواجهة الدائمة" },
  "ru-RU": { back: "Вернуться в рабочее пространство", account: "Аккаунт", appearance: "Внешний вид", language: "Язык", overview: "Обзор", history: "История", freeCredits: "Бесплатные кредиты", buyCredits: "Купить кредиты", wallet: "Кошелёк", credits: "Кредиты", walletDescription: "Здесь находятся кредиты вашего аккаунта.", available: "Всего доступно", dailyCredits: "Ежедневные кредиты", purchased: "Купленные", historyDescription: "Доходы и расходы аккаунта", freeDescription: "Ежедневные кредиты, приглашения и реклама", buyDescription: "Простые доступные пакеты", settings: "Настройки", settingsDescription: "Настройте аккаунт по отдельным разделам.", accountDescription: "Предпочтительное имя и данные аккаунта", appearanceDescription: "Светлая или тёмная тема", languageDescription: "Постоянный язык интерфейса" },
} satisfies Record<Language, Record<string, string>>;

type Key = keyof typeof text["en-US"];

export function tx(language: Language, key: Key): string {
  return text[language]?.[key] || text["en-US"][key];
}
