import { createFileRoute, Outlet, useLocation } from "@tanstack/react-router";
import { ArrowLeft, ChevronRight, Gift, History, ShoppingBag } from "lucide-react";
import { useCallback, useEffect, useState } from "react";
import { supabase } from "../lib/supabase";
import { CreditNav, InnerPage } from "../components/InnerPage";
import { availableCredits, effectiveDailyUsed, normalizeCreditWallet, type CreditWallet } from "../lib/credits";

export const Route = createFileRoute("/credits")({ component: Credits });
function Credits() { const location = useLocation(); const [wallet, setWallet] = useState<CreditWallet>(normalizeCreditWallet({ daily_credits_limit: 10 })); const load = useCallback(async () => { const { data: auth } = await supabase.auth.getUser(); if (!auth.user) return; const { data } = await supabase.from("ai_credits").select("free_credits,purchased_credits,total_credits,daily_credits_used,daily_credits_limit,daily_credits_reset_at").eq("user_id", auth.user.id).maybeSingle(); if (data) setWallet(normalizeCreditWallet(data)); }, []); useEffect(() => { void load(); const timer = window.setInterval(() => void load(), 15000); return () => window.clearInterval(timer); }, [load]); if (location.pathname !== "/credits") return <Outlet />; const dailyUsed = effectiveDailyUsed(wallet); const usable = availableCredits(wallet); return <InnerPage eyebrow="Wallet" title="Créditos" description="Aqui estão os créditos da sua conta."><CreditNav active="Overview" /><section className="rounded-3xl border border-violet-300/20 bg-gradient-to-br from-violet-500/[0.18] to-white/[0.04] p-6"><p className="text-sm text-white/50">Total disponível</p><p className="mt-1 text-5xl font-semibold">{usable.toFixed(2)}</p><div className="mt-5 grid grid-cols-3 gap-2"><div className="rounded-2xl bg-black/20 p-3"><p className="text-xs text-white/40">Créditos diários</p><p className="mt-1 font-semibold">{dailyUsed.toFixed(0)}/{wallet.daily_credits_limit >= 999999 ? "∞" : wallet.daily_credits_limit}</p></div><div className="rounded-2xl bg-black/20 p-3"><p className="text-xs text-white/40">Free</p><p className="mt-1 font-semibold">{wallet.free_credits.toFixed(2)}</p></div><div className="rounded-2xl bg-black/20 p-3"><p className="text-xs text-white/40">Purchased</p><p className="mt-1 font-semibold">{wallet.purchased_credits.toFixed(2)}</p></div></div></section><div className="mt-5 space-y-3"><a href="/credits/history" className="flex items-center gap-4 rounded-2xl border border-white/10 bg-white/[0.04] p-4 hover:bg-white/[0.08]"><History className="text-violet-300" size={21} /><span className="flex-1"><b className="block">Histórico</b><small className="text-white/40">Ganhos e gastos da sua conta</small></span><ChevronRight size={18} /></a><a href="/credits/free" className="flex items-center gap-4 rounded-2xl border border-white/10 bg-white/[0.04] p-4 hover:bg-white/[0.08]"><Gift className="text-amber-300" size={21} /><span className="flex-1"><b className="block">Créditos Gratuitos</b><small className="text-white/40">Daily credits, convites e anúncios</small></span><ChevronRight size={18} /></a><a href="/credits/buy" className="flex items-center gap-4 rounded-2xl border border-white/10 bg-white/[0.04] p-4 hover:bg-white/[0.08]"><ShoppingBag className="text-emerald-300" size={21} /><span className="flex-1"><b className="block">Comprar Créditos</b><small className="text-white/40">Pacotes simples e econômicos</small></span><ChevronRight size={18} /></a></div></InnerPage>; }
