import { Link } from "@tanstack/react-router";
import { Check, Moon, Sun, UserRound } from "lucide-react";
import { useEffect, useState } from "react";
import { supabase } from "../lib/supabase";
import { InnerPage, SettingsNav } from "../components/InnerPage";

function AccountPage() { const [name, setName] = useState(""); const [email, setEmail] = useState(""); const [saved, setSaved] = useState(false); useEffect(() => { void supabase.auth.getUser().then(({ data }) => { const user = data.user; if (!user) return; setEmail(user.email || ""); const metadata = user.user_metadata as { name?: string; display_name?: string } | undefined; setName(metadata?.name || metadata?.display_name || ""); }); }, []); const save = async () => { await supabase.auth.updateUser({ data: { name: name.trim(), display_name: name.trim() } }); localStorage.setItem("decidly-preferred-name", name.trim()); setSaved(true); window.setTimeout(() => setSaved(false), 1500); }; return <InnerPage eyebrow="Settings" title="Account" description="Gerencie seu nome de preferência e consulte os dados da conta."><SettingsNav active="Account" /><div className="rounded-3xl border border-white/10 bg-white/[0.035] p-6"><UserRound className="text-violet-300" /><label className="mt-6 block text-sm text-white/55">Preferred name<input value={name} onChange={(event) => setName(event.target.value)} className="mt-2 w-full rounded-2xl border border-white/10 bg-black/20 px-4 py-3 text-white outline-none focus:border-violet-300/50" /></label><label className="mt-4 block text-sm text-white/55">Email<input value={email} readOnly className="mt-2 w-full rounded-2xl border border-white/10 bg-white/[0.03] px-4 py-3 text-white/40" /></label><p className="mt-4 text-xs text-white/35">E-mail e senha não podem ser alterados nesta área.</p><button type="button" onClick={() => void save()} className="mt-6 inline-flex items-center gap-2 rounded-xl bg-violet-500 px-4 py-3 text-sm font-semibold">{saved ? <Check size={16} /> : null}{saved ? "Saved" : "Save name"}</button></div></InnerPage>; }

function AppearancePage() { const [theme, setTheme] = useState("dark"); useEffect(() => { void supabase.auth.getUser().then(({ data }) => { const metadata = data.user?.user_metadata as { theme?: string } | undefined; setTheme(metadata?.theme || localStorage.getItem("decidly-theme") || "dark"); }); }, []); const choose = async (next: string) => { setTheme(next); localStorage.setItem("decidly-theme", next); document.documentElement.dataset.theme = next; document.documentElement.classList.toggle("dark", next === "dark"); await supabase.auth.updateUser({ data: { theme: next } }); }; return <InnerPage eyebrow="Settings" title="Appearance" description="Escolha o tema permanente do DecidlyAI."><SettingsNav active="Appearance" /><div className="grid gap-3 sm:grid-cols-2"><button type="button" onClick={() => void choose("dark")} className={`rounded-3xl border p-6 text-left ${theme === "dark" ? "border-violet-300/50 bg-violet-400/[0.1]" : "border-white/10 bg-white/[0.035]"}`}><Moon className="text-violet-300" /><b className="mt-5 block">Dark</b><small className="mt-1 block text-white/40">Tema escuro do DecidlyAI</small></button><button type="button" onClick={() => void choose("light")} className={`rounded-3xl border p-6 text-left ${theme === "light" ? "border-violet-300/50 bg-violet-400/[0.1]" : "border-white/10 bg-white/[0.035]"}`}><Sun className="text-amber-300" /><b className="mt-5 block">Light</b><small className="mt-1 block text-white/40">Tema claro para todas as páginas</small></button></div></InnerPage>; }

function LanguagePage() { const [language, setLanguage] = useState("pt-BR"); useEffect(() => { void supabase.auth.getUser().then(({ data }) => { const metadata = data.user?.user_metadata as { language?: string } | undefined; setLanguage(metadata?.language || localStorage.getItem("decidly-language") || "pt-BR"); }); }, []); const choose = async (next: string) => { setLanguage(next); localStorage.setItem("decidly-language", next); document.documentElement.lang = next; await supabase.auth.updateUser({ data: { language: next } }); }; return <InnerPage eyebrow="Settings" title="Language" description="Sua escolha fica salva e será aplicada em todas as páginas compatíveis."><SettingsNav active="Language" /><div className="rounded-3xl border border-white/10 bg-white/[0.035] p-6"><label className="text-sm text-white/55">Interface language<select value={language} onChange={(event) => void choose(event.target.value)} className="mt-3 w-full rounded-2xl border border-white/10 bg-[#17101f] px-4 py-3 text-white outline-none"><option value="pt-BR">Português (Brasil)</option><option value="en-US">English (US)</option><option value="es-ES">Español</option></select></label><p className="mt-4 text-xs text-white/35">A preferência é persistente neste dispositivo e na sua sessão. O conteúdo será traduzido progressivamente.</p></div></InnerPage>; }

export { AccountPage, AppearancePage, LanguagePage };
