import { Check, Moon, Sun, UserRound } from "lucide-react";
import { useEffect, useState } from "react";
import { supabase } from "../lib/supabase";
import { LANGUAGES, isLanguage, type Language } from "../lib/i18n";
import { useLanguageContext } from "../lib/LanguageProvider";
import { InnerPage, SettingsNav } from "../components/InnerPage";
import { tx } from "../lib/localeText";
import { LanguageSelector } from "../components/LanguageSelector";

function AccountPage() { const { language } = useLanguageContext(); const [name, setName] = useState(""); const [email, setEmail] = useState(""); const [saved, setSaved] = useState(false); useEffect(() => { void supabase.auth.getUser().then(({ data }) => { const user = data.user; if (!user) return; setEmail(user.email || ""); const metadata = user.user_metadata as { name?: string; display_name?: string } | undefined; setName(metadata?.name || metadata?.display_name || ""); }); }, []); const save = async () => { const preferredName = name.trim(); const { data: auth } = await supabase.auth.getUser(); await supabase.auth.updateUser({ data: { name: preferredName, display_name: preferredName } }); if (auth.user) await supabase.from("profiles").update({ full_name: preferredName }).eq("id", auth.user.id); localStorage.setItem("decidly-preferred-name", preferredName); setSaved(true); window.setTimeout(() => setSaved(false), 1500); }; return <InnerPage eyebrow={tx(language, "settings")} title={tx(language, "account")} description={tx(language, "accountDescription")}><SettingsNav active="account" /><div className="rounded-3xl border border-white/10 bg-white/[0.035] p-6"><UserRound className="text-violet-300" /><label className="mt-6 block text-sm text-white/55">{language === "pt-BR" ? "Nome de preferência" : "Preferred name"}<input value={name} onChange={(event) => setName(event.target.value)} className="mt-2 w-full rounded-2xl border border-white/10 bg-black/20 px-4 py-3 text-white outline-none focus:border-violet-300/50" /></label><label className="mt-4 block text-sm text-white/55">Email<input value={email} readOnly className="mt-2 w-full rounded-2xl border border-white/10 bg-white/[0.03] px-4 py-3 text-white/40" /></label><p className="mt-4 text-xs text-white/35">{language === "pt-BR" ? "E-mail e senha não podem ser alterados nesta área." : "Email and password cannot be changed here."}</p><button type="button" onClick={() => void save()} className="mt-6 inline-flex items-center gap-2 rounded-xl bg-violet-500 px-4 py-3 text-sm font-semibold">{saved ? <Check size={16} /> : null}{saved ? (language === "pt-BR" ? "Salvo" : "Saved") : (language === "pt-BR" ? "Salvar nome" : "Save name")}</button></div></InnerPage>; }

function AppearancePage() { const { language } = useLanguageContext(); const [theme, setTheme] = useState("dark"); useEffect(() => { void supabase.auth.getUser().then(({ data }) => { const metadata = data.user?.user_metadata as { theme?: string } | undefined; setTheme(metadata?.theme || localStorage.getItem("decidly-theme") || "dark"); }); }, []); const choose = async (next: string) => { setTheme(next); localStorage.setItem("decidly-theme", next); document.documentElement.dataset.theme = next; document.documentElement.classList.toggle("dark", next === "dark"); await supabase.auth.updateUser({ data: { theme: next } }); }; return <InnerPage eyebrow={tx(language, "settings")} title={tx(language, "appearance")} description={tx(language, "appearanceDescription")}><SettingsNav active="appearance" /><div className="grid gap-3 sm:grid-cols-2"><button type="button" onClick={() => void choose("dark")} className={`rounded-3xl border p-6 text-left ${theme === "dark" ? "border-violet-300/50 bg-violet-400/[0.1]" : "border-white/10 bg-white/[0.035]"}`}><Moon className="text-violet-300" /><b className="mt-5 block">{language === "pt-BR" ? "Escuro" : "Dark"}</b><small className="mt-1 block text-white/40">{language === "pt-BR" ? "Tema escuro do DecidlyAI" : "DecidlyAI dark theme"}</small></button><button type="button" onClick={() => void choose("light")} className={`rounded-3xl border p-6 text-left ${theme === "light" ? "border-violet-300/50 bg-violet-400/[0.1]" : "border-white/10 bg-white/[0.035]"}`}><Sun className="text-amber-300" /><b className="mt-5 block">{language === "pt-BR" ? "Claro" : "Light"}</b><small className="mt-1 block text-white/40">{language === "pt-BR" ? "Tema claro para todas as páginas" : "Light theme for every page"}</small></button></div></InnerPage>; }

function LanguagePage() { const { language: currentLanguage, setLanguage: setGlobalLanguage } = useLanguageContext(); const [language, setLanguage] = useState<Language>(currentLanguage); useEffect(() => { void supabase.auth.getUser().then(({ data }) => { const metadata = data.user?.user_metadata as { language?: string } | undefined; const saved = metadata?.language || localStorage.getItem("decidly-language"); if (isLanguage(saved)) { setLanguage(saved); setGlobalLanguage(saved); } }); }, [setGlobalLanguage]); const choose = async (next: string) => { if (!isLanguage(next)) return; setLanguage(next); setGlobalLanguage(next); await supabase.auth.updateUser({ data: { language: next } }); }; return <InnerPage eyebrow={tx(language, "settings")} title={tx(language, "language")} description={tx(language, "languageDescription")}><SettingsNav active="language" /><div className="rounded-3xl border border-white/10 bg-white/[0.035] p-6"><div className="flex items-center justify-between gap-4"><div><p className="text-sm text-white/55">{tx(language, "languageLabel")}</p><p className="mt-1 text-sm text-white/35">{language === "pt-BR" ? "Escolha o idioma da interface" : "Choose the interface language"}</p></div><LanguageSelector onChange={(next) => void choose(next)} /></div><p className="mt-4 text-xs text-white/35">{language === "pt-BR" ? "A preferência fica salva neste dispositivo e na sua sessão." : "Your preference is saved on this device and in your session."}</p></div></InnerPage>; }

export { AccountPage, AppearancePage, LanguagePage };
