/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AiTestRouteImport } from './routes/ai-test'
import { Route as AjudaParaEscolherFaculdadeRouteImport } from './routes/ajuda-para-escolher-faculdade'
import { Route as BlogRouteImport } from './routes/blog'
import { Route as ComoFuncionaRouteImport } from './routes/como-funciona'
import { Route as ComoTomarDecisoesDificeisRouteImport } from './routes/como-tomar-decisoes-dificeis'
import { Route as CookiesRouteImport } from './routes/cookies'
import { Route as CreditsRouteImport } from './routes/credits'
import { Route as IaParaEmpreendedoresRouteImport } from './routes/ia-para-empreendedores'
import { Route as LoginRouteImport } from './routes/login'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as PromoRouteImport } from './routes/promo'
import { Route as ReferralHistoryRouteImport } from './routes/referral-history'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as TecnologiaRouteImport } from './routes/tecnologia'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as VipRouteImport } from './routes/vip'
import { Route as WorkspaceRouteImport } from './routes/workspace'
import { Route as AuthConfirmRouteImport } from './routes/auth.confirm'
import { Route as CreditsBuyRouteImport } from './routes/credits/buy'
import { Route as CreditsFreeRouteImport } from './routes/credits/free'
import { Route as CreditsHistoryRouteImport } from './routes/credits/history'
import { Route as PtBrCreditsRouteImport } from './routes/pt-br.credits'
import { Route as PtBrLoginRouteImport } from './routes/pt-br.login'
import { Route as PtBrSettingsRouteImport } from './routes/pt-br.settings'
import { Route as PtBrWorkspaceRouteImport } from './routes/pt-br.workspace'
import { Route as SettingsAccountRouteImport } from './routes/settings/account'
import { Route as SettingsAppearanceRouteImport } from './routes/settings/appearance'
import { Route as SettingsLanguageRouteImport } from './routes/settings/language'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AiTestRoute = AiTestRouteImport.update({
  id: '/ai-test',
  path: '/ai-test',
  getParentRoute: () => rootRouteImport,
} as any)
const AjudaParaEscolherFaculdadeRoute =
  AjudaParaEscolherFaculdadeRouteImport.update({
    id: '/ajuda-para-escolher-faculdade',
    path: '/ajuda-para-escolher-faculdade',
    getParentRoute: () => rootRouteImport,
  } as any)
const BlogRoute = BlogRouteImport.update({
  id: '/blog',
  path: '/blog',
  getParentRoute: () => rootRouteImport,
} as any)
const ComoFuncionaRoute = ComoFuncionaRouteImport.update({
  id: '/como-funciona',
  path: '/como-funciona',
  getParentRoute: () => rootRouteImport,
} as any)
const ComoTomarDecisoesDificeisRoute =
  ComoTomarDecisoesDificeisRouteImport.update({
    id: '/como-tomar-decisoes-dificeis',
    path: '/como-tomar-decisoes-dificeis',
    getParentRoute: () => rootRouteImport,
  } as any)
const CookiesRoute = CookiesRouteImport.update({
  id: '/cookies',
  path: '/cookies',
  getParentRoute: () => rootRouteImport,
} as any)
const CreditsRoute = CreditsRouteImport.update({
  id: '/credits',
  path: '/credits',
  getParentRoute: () => rootRouteImport,
} as any)
const IaParaEmpreendedoresRoute = IaParaEmpreendedoresRouteImport.update({
  id: '/ia-para-empreendedores',
  path: '/ia-para-empreendedores',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const PromoRoute = PromoRouteImport.update({
  id: '/promo',
  path: '/promo',
  getParentRoute: () => rootRouteImport,
} as any)
const ReferralHistoryRoute = ReferralHistoryRouteImport.update({
  id: '/referral-history',
  path: '/referral-history',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const TecnologiaRoute = TecnologiaRouteImport.update({
  id: '/tecnologia',
  path: '/tecnologia',
  getParentRoute: () => rootRouteImport,
} as any)
const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const VipRoute = VipRouteImport.update({
  id: '/vip',
  path: '/vip',
  getParentRoute: () => rootRouteImport,
} as any)
const WorkspaceRoute = WorkspaceRouteImport.update({
  id: '/workspace',
  path: '/workspace',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthConfirmRoute = AuthConfirmRouteImport.update({
  id: '/auth/confirm',
  path: '/auth/confirm',
  getParentRoute: () => rootRouteImport,
} as any)
const CreditsBuyRoute = CreditsBuyRouteImport.update({
  id: '/buy',
  path: '/buy',
  getParentRoute: () => CreditsRoute,
} as any)
const CreditsFreeRoute = CreditsFreeRouteImport.update({
  id: '/free',
  path: '/free',
  getParentRoute: () => CreditsRoute,
} as any)
const CreditsHistoryRoute = CreditsHistoryRouteImport.update({
  id: '/history',
  path: '/history',
  getParentRoute: () => CreditsRoute,
} as any)
const PtBrCreditsRoute = PtBrCreditsRouteImport.update({
  id: '/pt-br/credits',
  path: '/pt-br/credits',
  getParentRoute: () => rootRouteImport,
} as any)
const PtBrLoginRoute = PtBrLoginRouteImport.update({
  id: '/pt-br/login',
  path: '/pt-br/login',
  getParentRoute: () => rootRouteImport,
} as any)
const PtBrSettingsRoute = PtBrSettingsRouteImport.update({
  id: '/pt-br/settings',
  path: '/pt-br/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const PtBrWorkspaceRoute = PtBrWorkspaceRouteImport.update({
  id: '/pt-br/workspace',
  path: '/pt-br/workspace',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsAccountRoute = SettingsAccountRouteImport.update({
  id: '/account',
  path: '/account',
  getParentRoute: () => SettingsRoute,
} as any)
const SettingsAppearanceRoute = SettingsAppearanceRouteImport.update({
  id: '/appearance',
  path: '/appearance',
  getParentRoute: () => SettingsRoute,
} as any)
const SettingsLanguageRoute = SettingsLanguageRouteImport.update({
  id: '/language',
  path: '/language',
  getParentRoute: () => SettingsRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/ai-test': typeof AiTestRoute
  '/ajuda-para-escolher-faculdade': typeof AjudaParaEscolherFaculdadeRoute
  '/blog': typeof BlogRoute
  '/como-funciona': typeof ComoFuncionaRoute
  '/como-tomar-decisoes-dificeis': typeof ComoTomarDecisoesDificeisRoute
  '/cookies': typeof CookiesRoute
  '/credits': typeof CreditsRouteWithChildren
  '/ia-para-empreendedores': typeof IaParaEmpreendedoresRoute
  '/login': typeof LoginRoute
  '/privacy': typeof PrivacyRoute
  '/promo': typeof PromoRoute
  '/referral-history': typeof ReferralHistoryRoute
  '/reset-password': typeof ResetPasswordRoute
  '/settings': typeof SettingsRouteWithChildren
  '/tecnologia': typeof TecnologiaRoute
  '/terms': typeof TermsRoute
  '/vip': typeof VipRoute
  '/workspace': typeof WorkspaceRoute
  '/auth/confirm': typeof AuthConfirmRoute
  '/credits/buy': typeof CreditsBuyRoute
  '/credits/free': typeof CreditsFreeRoute
  '/credits/history': typeof CreditsHistoryRoute
  '/pt-br/credits': typeof PtBrCreditsRoute
  '/pt-br/login': typeof PtBrLoginRoute
  '/pt-br/settings': typeof PtBrSettingsRoute
  '/pt-br/workspace': typeof PtBrWorkspaceRoute
  '/settings/account': typeof SettingsAccountRoute
  '/settings/appearance': typeof SettingsAppearanceRoute
  '/settings/language': typeof SettingsLanguageRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/ai-test': typeof AiTestRoute
  '/ajuda-para-escolher-faculdade': typeof AjudaParaEscolherFaculdadeRoute
  '/blog': typeof BlogRoute
  '/como-funciona': typeof ComoFuncionaRoute
  '/como-tomar-decisoes-dificeis': typeof ComoTomarDecisoesDificeisRoute
  '/cookies': typeof CookiesRoute
  '/credits': typeof CreditsRouteWithChildren
  '/ia-para-empreendedores': typeof IaParaEmpreendedoresRoute
  '/login': typeof LoginRoute
  '/privacy': typeof PrivacyRoute
  '/promo': typeof PromoRoute
  '/referral-history': typeof ReferralHistoryRoute
  '/reset-password': typeof ResetPasswordRoute
  '/settings': typeof SettingsRouteWithChildren
  '/tecnologia': typeof TecnologiaRoute
  '/terms': typeof TermsRoute
  '/vip': typeof VipRoute
  '/workspace': typeof WorkspaceRoute
  '/auth/confirm': typeof AuthConfirmRoute
  '/credits/buy': typeof CreditsBuyRoute
  '/credits/free': typeof CreditsFreeRoute
  '/credits/history': typeof CreditsHistoryRoute
  '/pt-br/credits': typeof PtBrCreditsRoute
  '/pt-br/login': typeof PtBrLoginRoute
  '/pt-br/settings': typeof PtBrSettingsRoute
  '/pt-br/workspace': typeof PtBrWorkspaceRoute
  '/settings/account': typeof SettingsAccountRoute
  '/settings/appearance': typeof SettingsAppearanceRoute
  '/settings/language': typeof SettingsLanguageRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/ai-test': typeof AiTestRoute
  '/ajuda-para-escolher-faculdade': typeof AjudaParaEscolherFaculdadeRoute
  '/blog': typeof BlogRoute
  '/como-funciona': typeof ComoFuncionaRoute
  '/como-tomar-decisoes-dificeis': typeof ComoTomarDecisoesDificeisRoute
  '/cookies': typeof CookiesRoute
  '/credits': typeof CreditsRouteWithChildren
  '/ia-para-empreendedores': typeof IaParaEmpreendedoresRoute
  '/login': typeof LoginRoute
  '/privacy': typeof PrivacyRoute
  '/promo': typeof PromoRoute
  '/referral-history': typeof ReferralHistoryRoute
  '/reset-password': typeof ResetPasswordRoute
  '/settings': typeof SettingsRouteWithChildren
  '/tecnologia': typeof TecnologiaRoute
  '/terms': typeof TermsRoute
  '/vip': typeof VipRoute
  '/workspace': typeof WorkspaceRoute
  '/auth/confirm': typeof AuthConfirmRoute
  '/credits/buy': typeof CreditsBuyRoute
  '/credits/free': typeof CreditsFreeRoute
  '/credits/history': typeof CreditsHistoryRoute
  '/pt-br/credits': typeof PtBrCreditsRoute
  '/pt-br/login': typeof PtBrLoginRoute
  '/pt-br/settings': typeof PtBrSettingsRoute
  '/pt-br/workspace': typeof PtBrWorkspaceRoute
  '/settings/account': typeof SettingsAccountRoute
  '/settings/appearance': typeof SettingsAppearanceRoute
  '/settings/language': typeof SettingsLanguageRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/ai-test'
    | '/ajuda-para-escolher-faculdade'
    | '/blog'
    | '/como-funciona'
    | '/como-tomar-decisoes-dificeis'
    | '/cookies'
    | '/credits'
    | '/ia-para-empreendedores'
    | '/login'
    | '/privacy'
    | '/promo'
    | '/referral-history'
    | '/reset-password'
    | '/settings'
    | '/tecnologia'
    | '/terms'
    | '/vip'
    | '/workspace'
    | '/auth/confirm'
    | '/credits/buy'
    | '/credits/free'
    | '/credits/history'
    | '/pt-br/credits'
    | '/pt-br/login'
    | '/pt-br/settings'
    | '/pt-br/workspace'
    | '/settings/account'
    | '/settings/appearance'
    | '/settings/language'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/ai-test'
    | '/ajuda-para-escolher-faculdade'
    | '/blog'
    | '/como-funciona'
    | '/como-tomar-decisoes-dificeis'
    | '/cookies'
    | '/credits'
    | '/ia-para-empreendedores'
    | '/login'
    | '/privacy'
    | '/promo'
    | '/referral-history'
    | '/reset-password'
    | '/settings'
    | '/tecnologia'
    | '/terms'
    | '/vip'
    | '/workspace'
    | '/auth/confirm'
    | '/credits/buy'
    | '/credits/free'
    | '/credits/history'
    | '/pt-br/credits'
    | '/pt-br/login'
    | '/pt-br/settings'
    | '/pt-br/workspace'
    | '/settings/account'
    | '/settings/appearance'
    | '/settings/language'
  id:
    | '__root__'
    | '/'
    | '/ai-test'
    | '/ajuda-para-escolher-faculdade'
    | '/blog'
    | '/como-funciona'
    | '/como-tomar-decisoes-dificeis'
    | '/cookies'
    | '/credits'
    | '/ia-para-empreendedores'
    | '/login'
    | '/privacy'
    | '/promo'
    | '/referral-history'
    | '/reset-password'
    | '/settings'
    | '/tecnologia'
    | '/terms'
    | '/vip'
    | '/workspace'
    | '/auth/confirm'
    | '/credits/buy'
    | '/credits/free'
    | '/credits/history'
    | '/pt-br/credits'
    | '/pt-br/login'
    | '/pt-br/settings'
    | '/pt-br/workspace'
    | '/settings/account'
    | '/settings/appearance'
    | '/settings/language'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AiTestRoute: typeof AiTestRoute
  AjudaParaEscolherFaculdadeRoute: typeof AjudaParaEscolherFaculdadeRoute
  BlogRoute: typeof BlogRoute
  ComoFuncionaRoute: typeof ComoFuncionaRoute
  ComoTomarDecisoesDificeisRoute: typeof ComoTomarDecisoesDificeisRoute
  CookiesRoute: typeof CookiesRoute
  CreditsRoute: typeof CreditsRouteWithChildren
  IaParaEmpreendedoresRoute: typeof IaParaEmpreendedoresRoute
  LoginRoute: typeof LoginRoute
  PrivacyRoute: typeof PrivacyRoute
  PromoRoute: typeof PromoRoute
  ReferralHistoryRoute: typeof ReferralHistoryRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  SettingsRoute: typeof SettingsRouteWithChildren
  TecnologiaRoute: typeof TecnologiaRoute
  TermsRoute: typeof TermsRoute
  VipRoute: typeof VipRoute
  WorkspaceRoute: typeof WorkspaceRoute
  AuthConfirmRoute: typeof AuthConfirmRoute
  PtBrCreditsRoute: typeof PtBrCreditsRoute
  PtBrLoginRoute: typeof PtBrLoginRoute
  PtBrSettingsRoute: typeof PtBrSettingsRoute
  PtBrWorkspaceRoute: typeof PtBrWorkspaceRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ai-test': {
      id: '/ai-test'
      path: '/ai-test'
      fullPath: '/ai-test'
      preLoaderRoute: typeof AiTestRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ajuda-para-escolher-faculdade': {
      id: '/ajuda-para-escolher-faculdade'
      path: '/ajuda-para-escolher-faculdade'
      fullPath: '/ajuda-para-escolher-faculdade'
      preLoaderRoute: typeof AjudaParaEscolherFaculdadeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog': {
      id: '/blog'
      path: '/blog'
      fullPath: '/blog'
      preLoaderRoute: typeof BlogRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/como-funciona': {
      id: '/como-funciona'
      path: '/como-funciona'
      fullPath: '/como-funciona'
      preLoaderRoute: typeof ComoFuncionaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/como-tomar-decisoes-dificeis': {
      id: '/como-tomar-decisoes-dificeis'
      path: '/como-tomar-decisoes-dificeis'
      fullPath: '/como-tomar-decisoes-dificeis'
      preLoaderRoute: typeof ComoTomarDecisoesDificeisRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cookies': {
      id: '/cookies'
      path: '/cookies'
      fullPath: '/cookies'
      preLoaderRoute: typeof CookiesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/credits': {
      id: '/credits'
      path: '/credits'
      fullPath: '/credits'
      preLoaderRoute: typeof CreditsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ia-para-empreendedores': {
      id: '/ia-para-empreendedores'
      path: '/ia-para-empreendedores'
      fullPath: '/ia-para-empreendedores'
      preLoaderRoute: typeof IaParaEmpreendedoresRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/promo': {
      id: '/promo'
      path: '/promo'
      fullPath: '/promo'
      preLoaderRoute: typeof PromoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/referral-history': {
      id: '/referral-history'
      path: '/referral-history'
      fullPath: '/referral-history'
      preLoaderRoute: typeof ReferralHistoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tecnologia': {
      id: '/tecnologia'
      path: '/tecnologia'
      fullPath: '/tecnologia'
      preLoaderRoute: typeof TecnologiaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/vip': {
      id: '/vip'
      path: '/vip'
      fullPath: '/vip'
      preLoaderRoute: typeof VipRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/workspace': {
      id: '/workspace'
      path: '/workspace'
      fullPath: '/workspace'
      preLoaderRoute: typeof WorkspaceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/confirm': {
      id: '/auth/confirm'
      path: '/auth/confirm'
      fullPath: '/auth/confirm'
      preLoaderRoute: typeof AuthConfirmRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/credits/buy': {
      id: '/credits/buy'
      path: '/buy'
      fullPath: '/credits/buy'
      preLoaderRoute: typeof CreditsBuyRouteImport
      parentRoute: typeof CreditsRoute
    }
    '/credits/free': {
      id: '/credits/free'
      path: '/free'
      fullPath: '/credits/free'
      preLoaderRoute: typeof CreditsFreeRouteImport
      parentRoute: typeof CreditsRoute
    }
    '/credits/history': {
      id: '/credits/history'
      path: '/history'
      fullPath: '/credits/history'
      preLoaderRoute: typeof CreditsHistoryRouteImport
      parentRoute: typeof CreditsRoute
    }
    '/pt-br/credits': {
      id: '/pt-br/credits'
      path: '/pt-br/credits'
      fullPath: '/pt-br/credits'
      preLoaderRoute: typeof PtBrCreditsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pt-br/login': {
      id: '/pt-br/login'
      path: '/pt-br/login'
      fullPath: '/pt-br/login'
      preLoaderRoute: typeof PtBrLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pt-br/settings': {
      id: '/pt-br/settings'
      path: '/pt-br/settings'
      fullPath: '/pt-br/settings'
      preLoaderRoute: typeof PtBrSettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pt-br/workspace': {
      id: '/pt-br/workspace'
      path: '/pt-br/workspace'
      fullPath: '/pt-br/workspace'
      preLoaderRoute: typeof PtBrWorkspaceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings/account': {
      id: '/settings/account'
      path: '/account'
      fullPath: '/settings/account'
      preLoaderRoute: typeof SettingsAccountRouteImport
      parentRoute: typeof SettingsRoute
    }
    '/settings/appearance': {
      id: '/settings/appearance'
      path: '/appearance'
      fullPath: '/settings/appearance'
      preLoaderRoute: typeof SettingsAppearanceRouteImport
      parentRoute: typeof SettingsRoute
    }
    '/settings/language': {
      id: '/settings/language'
      path: '/language'
      fullPath: '/settings/language'
      preLoaderRoute: typeof SettingsLanguageRouteImport
      parentRoute: typeof SettingsRoute
    }
  }
}

interface CreditsRouteChildren {
  CreditsBuyRoute: typeof CreditsBuyRoute
  CreditsFreeRoute: typeof CreditsFreeRoute
  CreditsHistoryRoute: typeof CreditsHistoryRoute
}

const CreditsRouteChildren: CreditsRouteChildren = {
  CreditsBuyRoute: CreditsBuyRoute,
  CreditsFreeRoute: CreditsFreeRoute,
  CreditsHistoryRoute: CreditsHistoryRoute,
}

const CreditsRouteWithChildren =
  CreditsRoute._addFileChildren(CreditsRouteChildren)

interface SettingsRouteChildren {
  SettingsAccountRoute: typeof SettingsAccountRoute
  SettingsAppearanceRoute: typeof SettingsAppearanceRoute
  SettingsLanguageRoute: typeof SettingsLanguageRoute
}

const SettingsRouteChildren: SettingsRouteChildren = {
  SettingsAccountRoute: SettingsAccountRoute,
  SettingsAppearanceRoute: SettingsAppearanceRoute,
  SettingsLanguageRoute: SettingsLanguageRoute,
}

const SettingsRouteWithChildren = SettingsRoute._addFileChildren(
  SettingsRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AiTestRoute: AiTestRoute,
  AjudaParaEscolherFaculdadeRoute: AjudaParaEscolherFaculdadeRoute,
  BlogRoute: BlogRoute,
  ComoFuncionaRoute: ComoFuncionaRoute,
  ComoTomarDecisoesDificeisRoute: ComoTomarDecisoesDificeisRoute,
  CookiesRoute: CookiesRoute,
  CreditsRoute: CreditsRouteWithChildren,
  IaParaEmpreendedoresRoute: IaParaEmpreendedoresRoute,
  LoginRoute: LoginRoute,
  PrivacyRoute: PrivacyRoute,
  PromoRoute: PromoRoute,
  ReferralHistoryRoute: ReferralHistoryRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  SettingsRoute: SettingsRouteWithChildren,
  TecnologiaRoute: TecnologiaRoute,
  TermsRoute: TermsRoute,
  VipRoute: VipRoute,
  WorkspaceRoute: WorkspaceRoute,
  AuthConfirmRoute: AuthConfirmRoute,
  PtBrCreditsRoute: PtBrCreditsRoute,
  PtBrLoginRoute: PtBrLoginRoute,
  PtBrSettingsRoute: PtBrSettingsRoute,
  PtBrWorkspaceRoute: PtBrWorkspaceRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
